# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := gloox
LOCAL_HEAD_FILES := $(LOCAL_PATH)/gloox/gloox-api/native/com_idreamsky_gloox_GlooxNative.h \
					$(LOCAL_PATH)/gloox/gloox-api/inc/MessageExt.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/StringUtil.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/Packet.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/LogConfig.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/ServerConfig.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/JoinRoomListener.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/LeaveRoomListener.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/LoginListener.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/MessageReceiverListener.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/SendMessageListener.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/ChatClient.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/Skynet.h  \
					$(LOCAL_PATH)/gloox/gloox-api/inc/SkynetImpl.h  \
					$(LOCAL_PATH)/gloox/gloox/src/log.h  \
					$(LOCAL_PATH)/gloox/gloox/src/adhoc.h  \
					$(LOCAL_PATH)/gloox/gloox/src/adhoccommandprovider.h  \
					$(LOCAL_PATH)/gloox/gloox/src/adhochandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/amp.h  \
					$(LOCAL_PATH)/gloox/gloox/src/annotations.h  \
					$(LOCAL_PATH)/gloox/gloox/src/annotationshandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/atomicrefcount.h  \
					$(LOCAL_PATH)/gloox/gloox/src/attention.h  \
					$(LOCAL_PATH)/gloox/gloox/src/base64.h  \
					$(LOCAL_PATH)/gloox/gloox/src/bookmarkhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/bookmarkstorage.h  \
					$(LOCAL_PATH)/gloox/gloox/src/bytestream.h  \
					$(LOCAL_PATH)/gloox/gloox/src/bytestreamdatahandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/bytestreamhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/capabilities.h  \
					$(LOCAL_PATH)/gloox/gloox/src/carbons.h  \
					$(LOCAL_PATH)/gloox/gloox/src/chatstate.h  \
					$(LOCAL_PATH)/gloox/gloox/src/chatstatefilter.h  \
					$(LOCAL_PATH)/gloox/gloox/src/chatstatehandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/client.h  \
					$(LOCAL_PATH)/gloox/gloox/src/clientbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/component.h  \
					$(LOCAL_PATH)/gloox/gloox/src/compressionbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/compressiondatahandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/compressiondefault.h  \
					$(LOCAL_PATH)/gloox/gloox/src/compressionzlib.h  \
					$(LOCAL_PATH)/gloox/gloox/src/config.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionbosh.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiondatahandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionhttpproxy.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionlistener.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionsocks5proxy.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpclient.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpserver.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontls.h  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontlsserver.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dataform.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformfield.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformfieldcontainer.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformitem.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformreported.h  \
					$(LOCAL_PATH)/gloox/gloox/src/delayeddelivery.h  \
					$(LOCAL_PATH)/gloox/gloox/src/disco.h  \
					$(LOCAL_PATH)/gloox/gloox/src/discohandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/disconodehandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/dns.h  \
					$(LOCAL_PATH)/gloox/gloox/src/error.h  \
					$(LOCAL_PATH)/gloox/gloox/src/event.h  \
					$(LOCAL_PATH)/gloox/gloox/src/eventdispatcher.h  \
					$(LOCAL_PATH)/gloox/gloox/src/eventhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/featureneg.h  \
					$(LOCAL_PATH)/gloox/gloox/src/flexoff.h  \
					$(LOCAL_PATH)/gloox/gloox/src/flexoffhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/forward.h  \
					$(LOCAL_PATH)/gloox/gloox/src/gloox.h  \
					$(LOCAL_PATH)/gloox/gloox/src/glooxversion.h  \
					$(LOCAL_PATH)/gloox/gloox/src/gpgencrypted.h  \
					$(LOCAL_PATH)/gloox/gloox/src/gpgsigned.h  \
					$(LOCAL_PATH)/gloox/gloox/src/inbandbytestream.h  \
					$(LOCAL_PATH)/gloox/gloox/src/instantmucroom.h  \
					$(LOCAL_PATH)/gloox/gloox/src/iq.h  \
					$(LOCAL_PATH)/gloox/gloox/src/iqhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jid.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglecontent.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglefiletransfer.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jingleiceudp.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jingleplugin.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglepluginfactory.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglesession.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglesessionhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglesessionmanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/lastactivity.h  \
					$(LOCAL_PATH)/gloox/gloox/src/lastactivityhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocal.h  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocalclient.h  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocalhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocalmanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/loghandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/logsink.h  \
					$(LOCAL_PATH)/gloox/gloox/src/macros.h  \
					$(LOCAL_PATH)/gloox/gloox/src/md5.h  \
					$(LOCAL_PATH)/gloox/gloox/src/message.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messageevent.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messageeventfilter.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messageeventhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messagefilter.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messagehandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messagesession.h  \
					$(LOCAL_PATH)/gloox/gloox/src/messagesessionhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mucinvitationhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mucmessagesession.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mucroom.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mucroomconfighandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mucroomhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mutex.h  \
					$(LOCAL_PATH)/gloox/gloox/src/mutexguard.h  \
					$(LOCAL_PATH)/gloox/gloox/src/nickname.h  \
					$(LOCAL_PATH)/gloox/gloox/src/nonsaslauth.h  \
					$(LOCAL_PATH)/gloox/gloox/src/oob.h  \
					$(LOCAL_PATH)/gloox/gloox/src/parser.h  \
					$(LOCAL_PATH)/gloox/gloox/src/prep.h  \
					$(LOCAL_PATH)/gloox/gloox/src/presence.h  \
					$(LOCAL_PATH)/gloox/gloox/src/presencehandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/privacyitem.h  \
					$(LOCAL_PATH)/gloox/gloox/src/privacylisthandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/privacymanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/privatexml.h  \
					$(LOCAL_PATH)/gloox/gloox/src/privatexmlhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsub.h  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubevent.h  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubitem.h  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubmanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubresulthandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/receipt.h  \
					$(LOCAL_PATH)/gloox/gloox/src/registration.h  \
					$(LOCAL_PATH)/gloox/gloox/src/registrationhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/resource.h  \
					$(LOCAL_PATH)/gloox/gloox/src/rosteritem.h  \
					$(LOCAL_PATH)/gloox/gloox/src/rosteritemdata.h  \
					$(LOCAL_PATH)/gloox/gloox/src/rosterlistener.h  \
					$(LOCAL_PATH)/gloox/gloox/src/rostermanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/search.h  \
					$(LOCAL_PATH)/gloox/gloox/src/searchhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/sha.h  \
					$(LOCAL_PATH)/gloox/gloox/src/shim.h  \
					$(LOCAL_PATH)/gloox/gloox/src/sihandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/simanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/siprofileft.h  \
					$(LOCAL_PATH)/gloox/gloox/src/siprofilefthandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/siprofilehandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestream.h  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestreammanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestreamserver.h  \
					$(LOCAL_PATH)/gloox/gloox/src/softwareversion.h  \
					$(LOCAL_PATH)/gloox/gloox/src/stanza.h  \
					$(LOCAL_PATH)/gloox/gloox/src/stanzaextension.h  \
					$(LOCAL_PATH)/gloox/gloox/src/stanzaextensionfactory.h  \
					$(LOCAL_PATH)/gloox/gloox/src/statisticshandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/subscription.h  \
					$(LOCAL_PATH)/gloox/gloox/src/subscriptionhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tag.h  \
					$(LOCAL_PATH)/gloox/gloox/src/taghandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsdefault.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsclient.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsclientanon.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsserveranon.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlshandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslbase.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslclient.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslserver.h  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsschannel.h  \
					$(LOCAL_PATH)/gloox/gloox/src/uniquemucroom.h  \
					$(LOCAL_PATH)/gloox/gloox/src/util.h  \
					$(LOCAL_PATH)/gloox/gloox/src/vcard.h  \
					$(LOCAL_PATH)/gloox/gloox/src/vcardhandler.h  \
					$(LOCAL_PATH)/gloox/gloox/src/vcardmanager.h  \
					$(LOCAL_PATH)/gloox/gloox/src/vcardupdate.h  \
					$(LOCAL_PATH)/gloox/gloox/src/xhtmlim.h  \

LOCAL_SRC_FILES :=  $(LOCAL_PATH)/gloox/gloox-api/native/com_idreamsky_gloox_GlooxNative.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/MessageExt.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/StringUtil.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/Packet.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/ServerConfig.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/Skynet.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/SkynetImpl.cpp  \
					$(LOCAL_PATH)/gloox/gloox-api/src/ChatClient.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/adhoc.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/amp.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/annotations.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/atomicrefcount.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/attention.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/base64.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/bookmarkstorage.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/capabilities.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/carbons.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/chatstate.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/chatstatefilter.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/client.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/clientbase.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/component.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/compressiondefault.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/compressionzlib.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionbosh.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionhttpproxy.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectionsocks5proxy.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpbase.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpclient.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontcpserver.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontls.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/connectiontlsserver.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dataform.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformfield.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformfieldcontainer.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformitem.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dataformreported.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/delayeddelivery.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/disco.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/dns.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/error.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/eventdispatcher.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/featureneg.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/flexoff.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/forward.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/gloox.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/gpgencrypted.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/gpgsigned.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/inbandbytestream.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/instantmucroom.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/iq.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jid.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglecontent.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglefiletransfer.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jingleiceudp.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglepluginfactory.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglesession.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/jinglesessionmanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/lastactivity.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocalclient.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/linklocalmanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/logsink.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/md5.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/message.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/messageevent.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/messageeventfilter.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/messagefilter.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/messagesession.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/mucinvitationhandler.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/mucmessagesession.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/mucroom.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/mutex.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/nickname.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/nonsaslauth.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/oob.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/parser.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/prep.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/presence.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/privacyitem.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/privacymanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/privatexml.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubevent.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubitem.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/pubsubmanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/receipt.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/registration.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/rosteritem.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/rostermanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/search.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/sha.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/shim.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/simanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/siprofileft.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestream.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestreammanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/socks5bytestreamserver.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/softwareversion.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/stanza.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/stanzaextensionfactory.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/subscription.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tag.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsdefault.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsbase.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsclient.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsclientanon.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsgnutlsserveranon.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslbase.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslclient.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsopensslserver.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/tlsschannel.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/uniquemucroom.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/util.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/vcard.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/vcardmanager.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/vcardupdate.cpp  \
					$(LOCAL_PATH)/gloox/gloox/src/xhtmlim.cpp  \

LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
#include $(BUILD_STATIC_LIBRARY)
